///$tab Facts
Order:
LOAD CustomerID,
    EmployeeID,
    Freight,
    year(OrderDate)  as Year,
    month(OrderDate) as Month,
    day(OrderDate)   as Day,
    'Q'& ceil(month(OrderDate)/3) as Quarter,    //vypocitaj kvartal
    OrderID,
    ShipperID;
SQL SELECT 
*
FROM Orders;


[Order Details]:
LOAD 
	UnitPrice * (1-Discount)* Quantity as LineSales,
	Discount,
    LineNo,
    OrderID,
    ProductID,
    Quantity,
    UnitPrice;
SQL SELECT
*
FROM `Order Details`;